namespace: lab
namePrefix: microservice-
nameSuffix: -dev
bases:
- ../../base
patchesStrategicMerge:
- localserv.yaml

## no longer needed, use the namePrefix/nameSuffix to customize the name instead  
#patchesJSON6902:
#  - path: clustername.json
#    target:
#      group: postgres-operator.crunchydata.com
#      version: v1beta1
#      kind: PostgresCluster
#      name: ".*"
